# Generated by Django 4.1.3 on 2023-07-09 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication", old_name="description", new_name="author",
        ),
        migrations.AddField(
            model_name="publication",
            name="journal",
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=450),
        ),
    ]
