# Generated by Django 4.1.3 on 2022-12-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name="project", name="title", field=models.CharField(max_length=200),
        ),
    ]
